### ISSUE TITLE
Make enabled interceptors configurable

### ISSUE THREAD

**Issue by Ocramius** [Roave/StrictPhp#45]
As per current setup, StrictPhp is probably too strict for most libraries.

We may want to allow enabling/disabling of the various interceptors in StrictPhp.

A small "facade" in front of the singleton kernel may do the trick.

**Comment by ovr** [comment]
:+1:

**Comment by danizord** [comment]
"facade", mhmmm

![](http://40.media.tumblr.com/tumblr_lvrf58vBkL1qibz0jo1_r1_1280.png)

**Comment by Ocramius** [comment]
@danizord a real Façade, not a Laravel facade.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Ocramius** [comment]
`StrictPhp\StrictPhp::init([
    StrictPhp\StrictPhp::POST_CONSTRUCT_CHECKS,
    StrictPhp\StrictPhp::PARAMETER_INTERFACE_JAILING,
    StrictPhp\StrictPhp::PARAMETER_STRICT_TYPE_CHECKING,
    StrictPhp\StrictPhp::PROPERTY_WRITE_TYPE_CHECKING,
    StrictPhp\StrictPhp::POST_PUBLIC_METHOD_CALL_STATE_CHECKS,
    // ...
]);
```

**Comment by malukenho** [comment]
Closed as done in #48
