### ISSUE TITLE
Provide basic documentation

### ISSUE THREAD

**Issue by Ocramius** [Roave/StrictPhp#5]
Requires:

 - author references ( @ocramius and @malukenho )
 - description on how to enable it ( see https://github.com/Roave/StrictPhp/blob/d7a692967f0ecd04bf105dc9867ce3dc951ef8c6/test/functional/init.php )
 - link to a license (MIT please)
 - link to upgrade and contributing notes (also to be provided)

**Comment by Ocramius** [comment]
This is done

**Comment by GeeH** [comment]
If you want something doing, don't assign it to me.
