### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by janwalther** [Roave/StrictPhp#50]
I wonder why I cannot run the tests.
I installed PHPUnit and StrictPHP with composer (in require-dev). Then I ran 
```vendor/bin/phpunit vendor/roave/strict-php/```

But I get 
```Class 'StrictPhpTestAsset\ClassWithIncorrectlyInitializedParentClassProperties' not found in /path/to/my/project/vendor/roave/strict-php/tests/StrictPhpTest/AccessChecker/ObjectStateCheckerTest.php on line 81```

Is there an error or am I doing something wrong?
Or to ask the other way: How can I run all tests?

**Comment by Ocramius** [comment]
@janwalther tests are supposed to be run on a fresh clone, not in `vendor`

**Comment by janwalther** [comment]
Ah, thank you!
